micronaut:
  application:
    name: datasahi-siyadb
  server:
    cors:
      enabled: true
    port: ${DATASAHI_PORT:8081}
    dual-protocol: false

datasahi.siyadb:
  config:
    paths: ${DATASAHI_CONFIG_PATHS}
  work.dir: ${DATASAHI_WORK_DIR}